/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantallas;

import Cliente.Cliente;
import Dominio.Sensor;
import Server.Server;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class DetectarSensores extends javax.swing.JFrame {

    public static ArrayList<Sensor> sensoresSim = new ArrayList<>();

    public DetectarSensores() {
        initComponents();
        this.setLocationRelativeTo(null);
        iniciarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDetectados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listProvisional = new javax.swing.JList<>();
        btnAgrregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detectar Sensores");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sensores detectados");

        listDetectados.setModel(new DefaultListModel<>()
        );
        listDetectados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDetectadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listDetectados);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Lista Provisional");

        listProvisional.setModel(new DefaultListModel<>()
        );
        listProvisional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listProvisionalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listProvisional);

        btnAgrregar.setBackground(new java.awt.Color(153, 255, 153));
        btnAgrregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgrregar.setText("Agregar a Lista");
        btnAgrregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgrregar)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(btnAgrregar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listDetectadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDetectadosMouseClicked
        DefaultListModel<Sensor> model = (DefaultListModel<Sensor>) listDetectados.getModel();
        DefaultListModel<Sensor> modelP = (DefaultListModel<Sensor>) listProvisional.getModel();
        Sensor s = listDetectados.getSelectedValue();
        model.removeElement(s);
        modelP.addElement(s);
    }//GEN-LAST:event_listDetectadosMouseClicked

    private void listProvisionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProvisionalMouseClicked
        DefaultListModel<Sensor> model = (DefaultListModel<Sensor>) listDetectados.getModel();
        DefaultListModel<Sensor> modelP = (DefaultListModel<Sensor>) listProvisional.getModel();
        Sensor s = listDetectados.getSelectedValue();
        modelP.removeElement(s);
        model.addElement(s);
    }//GEN-LAST:event_listProvisionalMouseClicked

    private void btnAgrregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrregarActionPerformed
        ArrayList<Sensor> s = new ArrayList<>();
        DefaultListModel<Sensor> modelP = (DefaultListModel<Sensor>) listProvisional.getModel();

        for (int i = 0; i < modelP.getSize(); i++) {
            s.add(modelP.get(i));
        }
        MostrarSensores.sensores.addAll(s);
        if (!MostrarSensores.sensores.isEmpty()) {
            MostrarSensores.simularSensores(MostrarSensores.sensores);
            MostrarSensores.enviarDatosRest();
        }
        
        sensoresSim.removeAll(s);
        this.dispose();
    }//GEN-LAST:event_btnAgrregarActionPerformed

    private void getSensores() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    sensoresSim.addAll(new Server(3312, sensoresSim).RecibirListaDatos());
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }).start();
        try {
            TimeUnit.SECONDS.sleep(1);
        } catch (InterruptedException e) {
        }
        new Cliente("localhost", 3312).EnviarListaDatos();

        try {
            TimeUnit.SECONDS.sleep(1);
        } catch (InterruptedException e) {
        }
    }

    private void iniciarLista() {
        getSensores();
        DefaultListModel<Sensor> model = (DefaultListModel<Sensor>) listDetectados.getModel();
        if (model.isEmpty()) {
            for (Sensor sensor : sensoresSim) {
                model.addElement(sensor);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Sensor> listDetectados;
    private javax.swing.JList<Sensor> listProvisional;
    // End of variables declaration//GEN-END:variables
}
